### ISSUE TITLE
Privacy API not implemented

### ISSUE THREAD

**Issue by mudrd8mz** [jlohr-wiu7/moodle-local_intercom#1]
All plugins that interact with an external system, must have https://docs.moodle.org/dev/Privacy_API implemented correctly to be approved in the moodle plugins directory.

**Comment by jlohr-wiu7** [comment]
Would this fall under section 3 (Plugins that do not store personal data) since no data is stored within the plugin?  I didn't see an example of a plugin that sends data to an external system.

**Comment by mudrd8mz** [comment]
More likely https://docs.moodle.org/dev/Privacy_API#Indicating_that_you_export_data_to_an_external_location no?

**Comment by jlohr-wiu7** [comment]
Yes.  Sorry, I missed that.  Thanks.

**Comment by jlohr-wiu7** [comment]
Sorry for the lack of response, but is what is currently submitted acceptable?
