### ISSUE TITLE
Small error

### ISSUE THREAD

**Issue by shediac2** [jlohr-wiu7/moodle-local_intercom#3]
Getting an error 
 Non-static method local_intercom\helper::embed_intercom() should not be called statically in
intercom/lib.php on line 56

Line 56 is :$response = \local_intercom\helper::embed_intercom($context, $course);

Simple solution seems to be:
in classes/helper.php -  change function to static .

**Comment by jlohr-wiu7** [comment]
This should now be resolved in the changes to 0.1.3 that I just sent.
